repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Updated to a more recent, stable version
    rev: v0.5.5
    hooks:
        # Run the linter and fail if it applies fixes
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        # Run the formatter
    -   id: ruff-format
