repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. See https://github.com/astral-sh/ruff-pre-commit#versioning
    rev: v0.4.4
    hooks:
        # Run the linter.
        -   id: ruff
            args: [--fix]
        # Run the formatter.
        -   id: ruff-format
